# Site settings
title: Nick Goede
email: ngoede@gmail.com
description: > 
  Thoughts and ideas of one Nick Goede, professional
  software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.nickgoede.com" # the base hostname & protocol for your site
twitter_username: ngoede
github_username:  ngoede

# Build settings
markdown: kramdown

kramdown:
  input: GFM
paginate: 5

gems:
  [jekyll-sitemap, jekyll-paginate]